controllers/auth.py
from flask import Flask, render_template, url_for, request, redirect,get_flashed_messages, flash, Blueprint
from sqlalchemy.orm import Session
from models import engine, Usuario
from flask_login import LoginManager, login_user
from werkzeug.security import  check_password_hash  

auth_bp = Blueprint('auth',__name__,static_folder="static", template_folder="templates")

@auth_bp.route('/')
def index():
    return render_template('index.html')

@auth_bp.route('/login', methods = ['POST','GET'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        senha = request.form['senha']

        with Session(bind=engine) as session:
            usuario = session.query(Usuario).filter_by(email=email).first()
            if usuario and check_password_hash(usuario.senha, senha):
                login_user(usuario)
                return redirect(url_for('usuario.dashboard'))
            else:
                flash("Credenciais inválidas. Tente novamente.", "error")

    return render_template('login.html')

controllers/horario/__init__.py
from flask import Blueprint, request, flash, render_template, redirect, url_for
from sqlalchemy.orm import Session, joinedload,selectinload
from sqlalchemy import text, select
from models import Horarios, Usuarios, engine, aluno_horario
from flask_login import current_user
from datetime import datetime, date

horarios_bp = Blueprint('horario',__name__, template_folder = 'templates', static_folder = 'static')


@horarios_bp.route('/cadastrar_horario', methods = ['POST','GET'])
def cadastrar_horario():
    if request.method == 'POST':
        dia = request.form['dia']
        horario_inicio = request.form['horario_inicio']
        horario_termino = request.form['horario_termino']
        sala = request.form['sala']
        
        dia = datetime.strptime(dia, "%Y-%m-%d").date()
        horario_inicio = datetime.strptime(horario_inicio, "%H:%M").time()
        horario_termino = datetime.strptime(horario_termino, "%H:%M").time()
        with Session(bind=engine) as session:
            usuario = session.query(Usuarios).filter_by(id_usuario=current_user.id_usuario).first()
            if usuario.categoria != 'professor':
                flash("Apenas professores podem cadastrar horários.", 'error')

            else:
                novo_horario = Horarios(
                    dias=dia,
                    horario_inicio=horario_inicio,
                    horario_termino=horario_termino,
                    sala=sala,
                    id_professor = current_user.id_usuario)
                session.add(novo_horario)  
                session.commit()
                flash("Horário cadastrado com sucesso!", "success")
    
                return redirect(url_for('horario.listar_horarios'))
    return render_template("cadastro_horario.html", today=date.today().isoformat())

@horarios_bp.route('/listar_horarios')
def listar_horarios():
    with Session(bind=engine) as session:
        horarios = (session.query(Horarios).options(joinedload(Horarios.professor)).all())
        
        horarios_inscritos_ids = []
        if current_user.is_authenticated and current_user.categoria == 'aluno':
            stmt = select(aluno_horario.c.id_horario).where(aluno_horario.c.id_aluno == int(current_user.get_id()))
            result = session.execute(stmt).scalars().all()
            horarios_inscritos_ids = list(result)
            
    return render_template("listar_horarios.html", horarios=horarios, horarios_inscritos_ids=horarios_inscritos_ids)


@horarios_bp.route('/listar_participar')
def listar_participar():
    with Session(bind=engine) as session:
        horarios = (
        session.query(Horarios)
        .options(
            selectinload(Horarios.professor),
            selectinload(Horarios.alunos)
        )).all()
    return render_template('horarios_participando.html', horarios=horarios)



@horarios_bp.route('/participar_ca' ,methods = ['POST','GET'])
def participar_ca():
    horario_id = request.form['horario_id']


    with Session(bind= engine) as sessao:
        horario = sessao.query(Horarios).filter_by(id_horario = horario_id).first()
        if current_user in horario.alunos:
            flash('você ja esta cadastrado nesse CA', 'error')
            return redirect(url_for('horario.listar_horarios'))
        
        horario.alunos.append(current_user)
        sessao.commit()
        sessao.close()
    return redirect(url_for('horario.listar_participar'))


@horarios_bp.route('/excluir_ca', methods = ['POST','GET'])
def excluir_ca():
    if request.method != 'POST':
        return redirect(url_for('horario.listar_horarios'))

    horario_id = request.form.get('horario_id')
    if not horario_id:
        flash('ID do horário não informado.', 'error')
        return redirect(url_for('horario.listar_horarios'))

    with Session(bind=engine) as sessao:
        try:
            horario = sessao.query(Horarios).filter_by(id_horario=horario_id).first()
            if not horario:
                flash('Horário não encontrado.', 'error')
                return redirect(url_for('horario.listar_horarios'))

            if current_user.categoria != 'professor' or current_user.id_usuario != horario.id_professor:
                flash('Você não tem permissão para excluir este horário.', 'error')
                return redirect(url_for('horario.listar_horarios'))
            sessao.execute(text('DELETE FROM horarios WHERE id_horario = :id'), { 'id': horario_id })
            sessao.commit()
            flash('Horário excluído com sucesso.', 'success')
        except Exception as e:
            flash(f"Erro de integridade {e}", 'error')
        finally:
            sessao.close()
    return redirect(url_for('horario.listar_horarios'))


@horarios_bp.route('/participantes/<int:horario_id>')
def listar_participantes(horario_id):
    with Session(bind=engine) as session:
        horario = session.query(Horarios).options(
            selectinload(Horarios.alunos)
        ).filter_by(id_horario=horario_id).first()
        
        if not horario:
            flash("Horário não encontrado.", "error")
            return redirect(url_for('horario.listar_horarios'))
            
        return render_template('listar_participantes.html', horario=horario)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
</head>
<body>
    <div class="conteiner">
    <div class="navbar">
        <div class="nav">
        <a href="{{ url_for('auth.index') }}"><img src="{{ url_for('static', filename='css/imagens/logo.png') }}" alt="Logo" class="logo"></a>
        <ul>
            <li><a href="{{ url_for('horario.listar_horarios' ) }}">Horários</a></li>
            {% if not current_user.is_authenticated %}
                <li><a href="{{url_for('usuario.cadastro_usuario')}}">Cadastro</a></li> 
                <li><a href="{{url_for('auth.login')}}">Login</a></li>
            {% else %}
                <li><a href="{{url_for('usuario.dashboard')}}">Dashboard</a></li> 
                {% if current_user.categoria == "professor" %}
                    <li><a href="{{ url_for('horario.cadastrar_horario') }}">Cadastrar Horário</a></li>
                {% endif %}
                <li><a class = "logout-teste" href="{{ url_for('auth.logout' ) }}">Logout</a></li>
            {% endif %}
                
            
        </ul>   
        </div>
    </div>
    <div class="main">
    <div class="conteudo">
        {% include 'partials/erros.html' %}
        {% block conteudo %}
        {% endblock %}
    
    </div>
    </div>
    <div class="footer">
        Copyright © 2025 pratiCA
    </div>

    </div>
    </body>
</html>

templates/cadastro_aluno.html
{% extends "base.html" %} 

{%block title%} pratiCA {%endblock%}

{%block conteudo%}

<link rel="stylesheet" href="{{ url_for('static', filename='css/cadastro_aluno.css') }}">


<form action="" method="post">
    <h2>Cadastre-se</h2>
        <label for="matricula">Matricula</label>
        <input id="matricula" name="matricula" type="number" value="{{ request.form.matricula or '' }}">

        <label for="nome">Nome</label>    
        <input id="nome" name="nome" type="nome">

        <label for="senha">Senha</label>
        <input  id ="senha" name="senha"type="password">

      
        <label for="curso">Curso</label>
        <select name="curso" id="curso" required>
            <option value="">Selecione seu curso</option>
            {% for curso in cursos %}
                <option value="{{ curso.id }}">{{ curso.nome }}</option>
            {% endfor %}
        </select>


        <label for="ano">Ano</label>
        <select name="ano" id="ano" required>
            <option value="">Selecione seu ano</option>
            <option value="1° ano">1° ano</option>
            <option value="2° ano">2° ano</option>
            <option value="3° ano">3° ano</option>
            <option value="4° ano">4° ano</option>
        </select>

        
        <label for="turno">Turno</label>
        <select name="turno" id="turno" required>
            <option value="">Selecione seu turno</option>
            <option value="Matutino">Matutino</option>
            <option value="Vespertino">Vespertino</option>
        </select>
        <button type="submit">Enviar</button>
    </form>

{%endblock%}

templates/cadastro_horario.html
{% extends "base.html" %} 

{%block title%} pratiCA {%endblock%}

{% block conteudo %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/cadastro_horario.css') }}">

    <div class="cadastro-horario">
        <h3>Cadastrar Horario</h3>
        <form  method="POST" action="{{url_for('horario.cadastrar_horario')}}">

            <label for="dia" >Data</label>
            <input type="date" name="dia" id="dia" min ="{{ today }}">

            <label for="horario_inicio">Horario de inicio</label>
            <input type="text" name="horario_inicio" id="horario_inicio" placeholder="00:00">

            <label for="horario_termino">Horario de término</label>
            <input type="text" name="horario_termino" id="horario_termino" placeholder="00:00">

            <label for="sala">Sala</label>
            <select name="sala" id="sala" class="sala" >
                <option value="">Escolha uma sala</option>
                    <option value="a28">A28</option>
                    <option value="a26">A26</option>
                    <option value="f12">F12</option>
                    <option value="b5">B5</option>
                    <option value="b6">B6</option>
                    <option value="m4">M4</option>
                    <input type="submit" value="Criar CA">
            </select>
            </form>
    </div>
    
{% endblock %}

templates/cadastro_professor.html
{% extends "base.html" %} 

{%block title%} pratiCA {%endblock%}

{%block conteudo%}

<link rel="stylesheet" href="{{ url_for('static', filename='css/cadastro_professor.css') }}">


<form action="" method="post">
    <h2>Cadastre-se</h2>

    <label for="matricula">Matrícula</label>
    <input id="matricula" name="matricula" type="number" required>

    <label for="nome">Nome</label>    
    <input id="nome" name="nome" type="text" required>

    <label for="senha">Senha</label>
    <input id="senha" name="senha" type="password" required>

    <label for="disciplina">Disciplina</label>
    <select name="disciplina" id="disciplina" required>
    <option value="">Selecione uma disciplina</option>
        <option value="geografia">Geografia</option>
        <option value="historia">História</option>
        <option value="matematica">Matemática</option>
        <option value="portugues">Língua Portuguesa</option>
        <option value="ciencias">Ciências</option>
        <option value="biologia">Biologia</option>
        <option value="fisica">Física</option>
        <option value="quimica">Química</option>
        <option value="ingles">Inglês</option>
        <option value="educacao_fisica">Educação Física</option>
        <option value="artes">Artes</option>
        <option value="filosofia">Filosofia</option>
        <option value="sociologia">Sociologia</option>
    </select>
    <button type="submit">Cadastrar</button>
</form>


        
    

{%endblock%}

templates/cadastro_usuario.html
{% extends "base.html" %} 

{%block title%} pratiCA {%endblock%}

{%block conteudo%}


<link rel="stylesheet" href="{{ url_for('static', filename='css/cadastro_usuario.css') }}">

<div class="cadastro">
  <div class="title">
    <h1>Seu cargo na instituição</h1>
  </div>

  <div class="botoes">
    <a href="{{ url_for('usuario.cadastro_usuario', categoria='aluno') }}" class="botao_aluno">
      <div>Aluno</div>
    </a>

    <a href="{{ url_for('usuario.cadastro_usuario', categoria='professor') }}" class="botao_professor">
      <div>Professor</div>
    </a>
  </div>
</div>
{%endblock%}

templates/dashboard.html
{% extends "base.html" %} 

{%block title%} pratiCA {%endblock%}

{%block conteudo%}

<link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}">


<div class="wrapper">
    <div class="conteudo">
        <div class="painel">
            <div>
                <h4>Total de horarios</h4>
                <h5>{{total}}</h5>
            </div>
            <div>
                <h4>Ativos Hoje</h4>
                <h5>{{hoje}}</h5>
            </div>
            <div>
                <h4>Próximo</h4>
                {% if proximo %}
                    <h5>{{ proximo.dias }} - {{ proximo.horario_inicio }}</h5>
                {% else %}
                    <h5>—</h5>
                {% endif %}
            </div>
        </div>

       
        <!-- caixa que guarda as divs que vão redirecionar -->
        <div class="rotas">
            <!-- parte que somente professores conseguem fazer -->
            {% if current_user.categoria == "professor" %}

                <div>
                    <h3>Meus horários</h3>
                    <p>Aqui o professor vê os horários que cadastrou.</p>
                    <a href="{{url_for('horario.listar_horarios')}}" class="btn btn-primary">Horários cadastrados</a>
                </div>

                <div>
                    <h3>Cadastrar CA</h3>
                    <p>O professor pode cadastrar novos horários de CA.</p>
                    <a href="{{ url_for('horario.cadastrar_horario') }}" class="btn btn-primary">
                        Cadastrar CA
                    </a>
                </div>

            {% endif %}
            <!-- parte que somente alunos podem fazer -->
            {% if current_user.categoria == "aluno" %}

                <div>
                    <h3>CAs disponíveis</h3>
                    <p>Horários disponíveis para o aluno se inscrever.</p>
                    <a href="{{ url_for('horario.listar_horarios') }}" class="btn btn-primary">
                        CAs disponíveis
                    </a>
                </div>

                <div>
                    <h3>CAs que participarei</h3>
                    <p>Horários nos quais o aluno já está inscrito.</p>
                    <a href="{{ url_for('horario.listar_participar') }}" class="btn btn-primary">CAs futuros</a>
                </div>

            {% endif %}
        </div>
        
    </div>
</div>

{%endblock%}

templates/erro_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Erro {{ erro }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/erro_base.css') }}">
</head>
<body>
    <h1>Erro {{ erro }}</h1>
    <p>{{ mensagem }}</p>
    
    <img src="{{ url_for('static', filename='css/imagens/erro.png') }}" alt="Imagem de erro" class="erro-imagem">

    <a href="{{ url_for('auth.login') }}">Voltar</a>
</body>
</html>

templates/horarios_participando.html
{% extends 'base.html' %}

{% block conteudo %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/listar_horarios.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}">

    <div class="horarios-cadastrados">
        <h1>Horários Participando</h1>
        
        <table>
            <tr>
                <th>Dia</th>
                <th>Inicio</th>
                <th>Término</th>
                <th>Sala</th>
                <th>Professor Responsável</th>
            </tr>
            {% for horario in horarios %}
            <tr>
                <td>{{ horario.dias }}</td>
                <td>{{ horario.horario_inicio }}</td>
                <td>{{ horario.horario_termino }}</td>
                <td>{{ horario.sala }}</td>
                <td>{{ horario.professor.nome}}</td>
            </tr>
            {% else %}
            <tr>
                <td colspan="6">Nenhum horário cadastrado.</td>
            </tr>
            {% endfor %}
        </table>
</div>


{% endblock %}

templates/index.html
{% extends "base.html" %} 

{%block title%} pratiCA {%endblock%}

{%block conteudo%}

<link rel="stylesheet" href="{{ url_for('static', filename='css/inicial.css') }}">

<section class="container-inicial">
    <h1>Seja muito bem-vindo ao <span class="destaque">pratiCA</span>!</h1>
    <img src="{{ url_for('static', filename='css/imagens/logomarca.png') }}" alt="marca" class="logomarca">

</section>

<section class="container-principal">
    <div class="blocos1">
        <div class="bloco1">
            <h3>Inovação</h3>
            <p>Nosso sistema busca inovar a estrutura das atividades de CA</p>
        </div>
        <div class="bloco1">
            <h3>Organização</h3>
            <p>Na nossa plataforma, os horarios de CA serão organizados de maneira
                a facilitar a organização da atividade
            </p>
        </div>
        <div class="bloco1">
            <h3>Praticidade</h3>
            <p>Sistema de facil utilização e compreensão</p>
        </div>
    </div>
    <div class="bloco2">
        <h3>Vamos Começar?</h3>
        <p class= "texto">Comece agora a organizar seus horários!</p>
        <a href="{{url_for('usuario.dashboard')}}" class="btn">Começar agora</a>
    </div>
    </div>
</section>

<section class="container-final">
</section>

{%endblock%}

templates/listar_horarios.html
{% extends "base.html" %} 

{%block title%} pratiCA {%endblock%}

{%block conteudo%}

<link rel="stylesheet" href="{{ url_for('static', filename='css/listar_horarios.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/listar_participantes.css') }}">

<div class="horarios-cadastrados">
    <h1>Horários Cadastrados</h1>
    
    <table>
        <tr>
            <th>Dia</th>
            <th>Inicio</th>
            <th>Término</th>
            <th>Sala</th>
            <th>Professor Responsável</th>
            <th>Ações</th>
        </tr>
        {% for horario in horarios %}
            <tr>
                <td>{{ horario.dias }}</td>
                <td>{{ horario.horario_inicio }}</td>
                <td>{{ horario.horario_termino }}</td>
                <td>{{ horario.sala }}</td>
                <td>{{ horario.professor.nome}}</td>
                <td class="acoes-container">
                    {% if current_user.categoria == "professor" %}
                        {% if current_user.id_usuario == horario.id_professor %}
                            <form action="{{ url_for('horario.excluir_ca') }}" method="POST">
                                <input type="hidden" name="horario_id" value="{{ horario.id_horario }}">
                                <input type="submit" value="Excluir" class="botao-excluir">
                            </form>
                        {% endif %}
                        <a href="{{ url_for('horario.listar_participantes', horario_id=horario.id_horario) }}" class="botao-participantes">Participantes</a>
                    {% elif current_user.categoria == "aluno" %}
                        {% if horarios_inscritos_ids is defined and horario.id_horario in horarios_inscritos_ids %}
                            <button class="btn" style="background-color: #d5f2dcff" disabled>Inscrito</button>
                        {% else %}
                            <form class="btn btn-participar-aluno" action="{{ url_for('horario.participar_ca') }}" method="POST">
                                <input type="hidden" name="horario_id" value="{{ horario.id_horario }}">
                                <input type="submit" value="Participar" class="botao-participar">
                            </form>
                        {% endif %}
                        <a href="{{ url_for('horario.listar_participantes', horario_id=horario.id_horario) }}" class="botao-participantes">Participantes</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Nenhum horário cadastrado.</td>
            </tr>
        {% endfor %}
    </table>
</div>

{%endblock%}

templates/listar_participantes.html
{% extends "base.html" %} 

{%block title%} Participantes - pratiCA {%endblock%}

{%block conteudo%}

<link rel="stylesheet" href="{{ url_for('static', filename='css/listar_horarios.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/listar_participantes.css') }}">

<div class="horarios-cadastrados">
    <h1>Alunos confirmados</h1>
    
    <div class="info">
        <p><strong>Dia:</strong> {{ horario.dias }}</p>
        <p><strong>Horário:</strong> {{ horario.horario_inicio }} - {{ horario.horario_termino }}</p>
        <p><strong>Sala:</strong> {{ horario.sala }}</p>
    </div>

   <div class="lista_presenca"> <h2>Lista de presença ({{ horario.alunos|length }})</h2></div>

    <div class="lista-participantes">
        <table>
            <tr>
                <th>Matrícula</th>
                <th>Nome do Aluno</th>
                <th>Curso</th>
                <th>Turno</th>
            </tr>
            {% for aluno in horario.alunos %}
            <tr>
                <td>{{ aluno.matricula }}</td>
                <td>{{ aluno.nome }}</td>
                <td>{{ aluno.curso.nome }}</td>
                <td>{{ aluno.turno }}</td>
            </tr>
            {% else %}
            <tr>
                <td colspan="4">ainda não há alunos inscritos para este horário.</td>
            </tr>
            {% endfor %}
        </table>
    </div>

    <div class="voltar">
        <a href="{{ url_for('horario.listar_horarios') }}" class="voltar-botao">Voltar para horários</a>
    </div>
</div>

{%endblock%}

templates/login.html
{% extends "base.html" %} 

{%block title%} pratiCA {%endblock%}

{%block conteudo%}

<link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">


<form action="" method="post">

        <label for="email">E-mail</label>
        <input id="email" name="email" type="email" required placeholder="seu@exemplo.com" value="{{ request.form.email or '' }}">

        <label for="senha">Senha</label>
        <input  id ="senha" name="senha"type="password">
         <button type="submit">Enviar</button>
    </form>

{%endblock%}